on: [push]

jobs:
  hello_world_job:
    runs-on: macOS-latest
    name: A job to say hello
    steps:
      - id: start_desktop
        uses: gtardif/desktop-action@0.0.4-beta-2
      - run: docker version
