on: [push]

jobs:
  hello_world_job:
    runs-on: macOS-latest
    name: install Docker desktop
    steps:
      - id: start_desktop
        uses: docker/desktop-action/start@v0.0.1
      - run: docker version
